name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 24.5
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'
    - uses: actions/checkout@v2
    - name: Print Emacs version
      run: |
        emacs --version
    - name: Run tests
      run: |
        cask
        cask exec buttercup -L .
